// <auto-generated />
using System;
using Api.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Persistencia.Migraciones
{
    [DbContext(typeof(GestionPedidoDbContext))]
    [Migration("20241128140812_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Dominio.Central", b =>
                {
                    b.Property<int>("IdCentral")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCentral"));

                    b.Property<int>("DomicilioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCentral");

                    b.HasIndex("DomicilioId");

                    b.ToTable("Centrales");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Domicilio", b =>
                {
                    b.Property<int>("IdDomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDomicilio"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDomicilio");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Envio", b =>
                {
                    b.Property<int>("NumeroSeguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroSeguimiento"));

                    b.Property<int>("CentralDespachoId")
                        .HasColumnType("int");

                    b.Property<int>("CentralDestinoId")
                        .HasColumnType("int");

                    b.Property<string>("Dimensiones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPersonaEmisora")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonaReceptora")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SucursalDespachoId")
                        .HasColumnType("int");

                    b.Property<int>("SucursalDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("estadoEnvio")
                        .HasColumnType("int");

                    b.Property<int>("personaEmisoraIdPersona")
                        .HasColumnType("int");

                    b.Property<int>("personaReceptoraIdPersona")
                        .HasColumnType("int");

                    b.HasKey("NumeroSeguimiento");

                    b.HasIndex("CentralDespachoId");

                    b.HasIndex("CentralDestinoId");

                    b.HasIndex("SucursalDespachoId");

                    b.HasIndex("SucursalDestinoId");

                    b.HasIndex("personaEmisoraIdPersona");

                    b.HasIndex("personaReceptoraIdPersona");

                    b.ToTable("Envios");
                });

            modelBuilder.Entity("Biblioteca.Dominio.HistorialEnvio", b =>
                {
                    b.Property<int>("IdHistorialEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorialEnvio"));

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroSeguimiento")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.Property<int>("envioNumeroSeguimiento")
                        .HasColumnType("int");

                    b.Property<int>("estadoEnvio")
                        .HasColumnType("int");

                    b.HasKey("IdHistorialEnvio");

                    b.HasIndex("SucursalId");

                    b.HasIndex("envioNumeroSeguimiento");

                    b.ToTable("HistorialesEnvio");
                });

            modelBuilder.Entity("Biblioteca.Dominio.IntentoEntrega", b =>
                {
                    b.Property<int>("IdIntentoEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIntentoEntrega"));

                    b.Property<bool>("Entregado")
                        .HasColumnType("bit");

                    b.Property<int>("EnvioNumeroSeguimiento")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroIntento")
                        .HasColumnType("int");

                    b.Property<int>("NumeroSeguimiento")
                        .HasColumnType("int");

                    b.Property<int>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("IdIntentoEntrega");

                    b.HasIndex("EnvioNumeroSeguimiento");

                    b.HasIndex("SucursalId");

                    b.ToTable("IntentosEntrega");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<int>("DomicilioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisResidente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDNIId")
                        .HasColumnType("int");

                    b.HasKey("IdPersona");

                    b.HasIndex("DomicilioId");

                    b.HasIndex("TipoDNIId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<int>("DomicilioId")
                        .HasColumnType("int");

                    b.Property<int>("IdCentral")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroS")
                        .HasColumnType("int");

                    b.HasKey("IdSucursal");

                    b.HasIndex("DomicilioId");

                    b.HasIndex("IdCentral");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Biblioteca.Dominio.TipoDNI", b =>
                {
                    b.Property<int>("IdTipoDni")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDni"));

                    b.Property<bool>("DNIextranjero")
                        .HasColumnType("bit");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoDni");

                    b.ToTable("TipoDNI");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Central", b =>
                {
                    b.HasOne("Biblioteca.Dominio.Domicilio", "domicilio")
                        .WithMany()
                        .HasForeignKey("DomicilioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("domicilio");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Envio", b =>
                {
                    b.HasOne("Biblioteca.Dominio.Central", "centralDespacho")
                        .WithMany()
                        .HasForeignKey("CentralDespachoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Central", "centralDestino")
                        .WithMany()
                        .HasForeignKey("CentralDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Sucursal", "sucursalDespacho")
                        .WithMany()
                        .HasForeignKey("SucursalDespachoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Sucursal", "sucursalDestino")
                        .WithMany()
                        .HasForeignKey("SucursalDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Persona", "personaEmisora")
                        .WithMany()
                        .HasForeignKey("personaEmisoraIdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Persona", "personaReceptora")
                        .WithMany()
                        .HasForeignKey("personaReceptoraIdPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("centralDespacho");

                    b.Navigation("centralDestino");

                    b.Navigation("personaEmisora");

                    b.Navigation("personaReceptora");

                    b.Navigation("sucursalDespacho");

                    b.Navigation("sucursalDestino");
                });

            modelBuilder.Entity("Biblioteca.Dominio.HistorialEnvio", b =>
                {
                    b.HasOne("Biblioteca.Dominio.Sucursal", "sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Envio", "envio")
                        .WithMany("Historiales")
                        .HasForeignKey("envioNumeroSeguimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("envio");

                    b.Navigation("sucursal");
                });

            modelBuilder.Entity("Biblioteca.Dominio.IntentoEntrega", b =>
                {
                    b.HasOne("Biblioteca.Dominio.Envio", "Envio")
                        .WithMany()
                        .HasForeignKey("EnvioNumeroSeguimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Sucursal", "sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envio");

                    b.Navigation("sucursal");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Persona", b =>
                {
                    b.HasOne("Biblioteca.Dominio.Domicilio", "domicilio")
                        .WithMany()
                        .HasForeignKey("DomicilioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.TipoDNI", "TipoDNI")
                        .WithMany()
                        .HasForeignKey("TipoDNIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDNI");

                    b.Navigation("domicilio");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Sucursal", b =>
                {
                    b.HasOne("Biblioteca.Dominio.Domicilio", "domicilio")
                        .WithMany()
                        .HasForeignKey("DomicilioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Biblioteca.Dominio.Central", "Central")
                        .WithMany("Sucursales")
                        .HasForeignKey("IdCentral")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Central");

                    b.Navigation("domicilio");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Central", b =>
                {
                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("Biblioteca.Dominio.Envio", b =>
                {
                    b.Navigation("Historiales");
                });
#pragma warning restore 612, 618
        }
    }
}
